version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
    container_name: twitter-api
    hostname: twitter-api
    networks:
      - mynet
    ports:
      - 80:8080
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13-alpine
    restart: always 
    env_file:
      - .env.docker
    ports:
      - 5433:5432
      - 8080:8080
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet
    container_name: twitter-db

volumes:
  postgres_data:

networks:
  mynet:
    driver: bridge
