##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./

RUN go build -o /twitter-clone

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /twitter-clone /twitter-clone

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/twitter-clone"]
